oms:
  greetings: Hello From OMS
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

kafka:
  bootstrap-servers: localhost:9092
  invetory-topic: inventory-topic
  order-topic: order-topic

spring:
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
