server:
  servlet:
    context-path: /order-service
  port: 8082

springdoc:
  version: 1.0
  title: Order Service API
  description: Order Service API Documentation

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   consumer:
  #     group-id: order-service
  #     auto-offset-reset: earliest
  #     enable-auto-commit: false
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #   consumer:
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
